version: '3.8'

services:
  backend:
    image: oven/bun:1.1.12
    container_name: ema-backend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=elliesdb
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=PruebaSuperSecreta
    command: sh -c "bun install && bun index.js"

  backend-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ema-backend-test
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: ema-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elliesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data: